[package]
name = "input_method_service"
version = "0.1.0"
authors = ["pentamassiv <pentamassiv@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wayland-client = {version="0.27", features = ["use_system_lib"]}
wayland-protocols = {version="0.27", features = ["client", "unstable_protocols"]}
zwp-virtual-keyboard = "0.1"
input_event_codes_hashmap = "0.1.0"
zwp-input-method = "0.1.0"